services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: patient_management
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patient_management_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U patient_management"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: >
      sh -c "
        echo 'Waiting for database to be ready...'
        until pg_isready -h db -U patient_management; do
          sleep 2
        done &&
        echo 'Database is ready!' &&
        bundle exec rails db:create db:migrate &&
        rm -f tmp/pids/server.pid &&
        echo 'Starting Rails server...' &&
        bundle exec rails server -p 3000 -b '0.0.0.0'
      "
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://patient_management:password@db:5432/patient_management_development
      RAILS_ENV: development

volumes:
  postgres_data: